$(document).ready(function (){
  $("#cuteclick").click(function(){
    $("#cutepanel").slideDown();
  });
  $("#trashclick").click(function(){
    $("#trashpanel").slideDown();
  });
  $("#worldclick").click(function(){
    $("#worldpanel").slideDown();
  });
  $("#cuteclose").click(function(){
    $("#cutepanel").slideUp();
  });
  $("#trashclose").click(function(){
    $("#trashpanel").slideUp();
  });
  $("#worldclose").click(function(){
    $("#worldpanel").slideUp();
  });
});
